export const FRASES_ESTOICAS = [
  "No busques que los eventos sucedan como tú deseas, sino desea que sucedan como suceden, y encontrarás la paz. — Epicteto",
  "La felicidad de tu vida depende de la calidad de tus pensamientos. — Marco Aurelio",
  "No nos afecta lo que nos sucede, sino lo que nos decimos acerca de lo que nos sucede. — Epicteto",
  "El que teme a la muerte, nunca hará nada digno del hombre que está vivo. — Séneca",
  "No malgastes más tiempo argumentando acerca de lo que debe ser un buen hombre. Sé uno. — Marco Aurelio",
  "Elige no ser dañado y no te sentirás dañado. No te sientas dañado y no lo habrás sido. — Marco Aurelio",
  "A menudo sufrimos más en la imaginación que en la realidad. — Séneca",
  "Un barco no debería navegar con una sola ancla, ni la vida con una sola esperanza. — Epicteto",
  "La mejor venganza es ser diferente a quien realizó el daño. — Marco Aurelio",
  "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad. — Séneca",
  "Es esencial que recuerdes que la atención que le des a cualquier acción debe ser proporcional a su valor. — Marco Aurelio",
  "Si no está bien, no lo hagas. Si no es verdad, no lo digas. — Marco Aurelio",
  "No exige tanto de los demás como te exiges a ti mismo. — Marco Aurelio",
  "La riqueza no consiste en tener grandes posesiones, sino en tener pocas necesidades. — Epicteto",
  "La vida es muy corta y angustiosa para aquellos que olvidan el pasado, descuidan el presente y temen el futuro. — Séneca",
  "Ninguna persona es libre si no es dueña de sí misma. — Epicteto",
  "No te detengas en pensar que las cosas serán como quieres. Aprende a querer las cosas como son. — Séneca",
  "El obstáculo es el camino. Lo que impide la acción avanza la acción. Lo que se interpone en el camino se convierte en el camino. — Marco Aurelio",
  "Haz cada cosa en la vida como si fuera lo último que vayas a hacer. — Marco Aurelio",
  "La tranquilidad no es otra cosa que el buen orden de la mente. — Marco Aurelio",
  "Si quieres ser bueno, primero cree que eres malo. — Epicteto",
  "Dificultades muestran lo que son los hombres. — Epicteto",
  "Solamente hay una manera de alcanzar la felicidad y es dejar de preocuparse por cosas que están más allá del poder o de nuestra voluntad. — Epicteto",
  "El sabio está contento con su suerte, sea cual sea, sin desear lo que no tiene. — Séneca",
  "Tienes poder sobre tu mente, no sobre los eventos externos. Date cuenta de esto, y encontrarás la fuerza. — Marco Aurelio",
  "Pocas cosas son necesarias para hacer una vida feliz; todo está dentro de ti, en tu forma de pensar. — Marco Aurelio",
  "Quien es valiente, es libre. — Séneca",
  "Es propio del hombre noble el ser sereno y estar dispuesto a perdonar. — Séneca",
  "Todo lo que escuchamos es una opinión, no un hecho. Todo lo que vemos es una perspectiva, no la verdad. — Marco Aurelio",
  "Ningún hombre es bueno por casualidad. La virtud se debe aprender. — Séneca",
  "Controla tus pasiones para que no te controlen a ti. — Epicteto",
  "Piensa en la belleza de la vida. Mira las estrellas y vete corriendo con ellas. — Marco Aurelio",
  "El hombre que ha anticipado la llegada de los problemas, le quita poder cuando éstos llegan. — Séneca",
  "Comienza a vivir de inmediato y cuenta cada día como una vida separada. — Séneca",
  "La ira siempre es más dañina que la ofensa que la provocó. — Marco Aurelio",
  "Recibe la riqueza o la prosperidad sin arrogancia y prepárate a dejarla ir sin tristeza. — Marco Aurelio",
  "Sé tolerante con los demás y estricto contigo mismo. — Marco Aurelio",
  "Para ser feliz hay que entender primero qué es lo que puedes controlar y qué no. — Epicteto",
  "Acepta todo lo que te llegue entretejido en el patrón de tu destino, porque, ¿qué podría encajar mejor en tus necesidades? — Marco Aurelio",
  "No espere que se cumpla lo que tienes en el corazón, sino desea el bien de las personas. — Marco Aurelio",
  "Que no te venza la fatiga ni permitas que los reveses apaguen tu fuego interior. — Séneca"
];
